v2.0.0-beta.1 (#37)
* chore: draft for multiarch image

* refactor: dockerfiles & fix openssl3 binary for x86_64/arm64 darwin

* chore: update joseluisq/docker-osxcross to 1.0.0-beta.2

* chore: add project dir for tests

* fix: makefile test tasks and arm64 Dockerfile

* chore: add missing x86_64 toolchain

* chore: fix amd64 and arm64 docker images tests

* fix: linux x86_64 openssl build for docker arm64 image

* fix: CI 'no space left on device' issue

------
 > exporting to docker image format:
------
------
 > importing to docker:
------
ERROR: failed to build: failed to solve: rpc error: code = Unknown desc = write /root/.rustup/toolchains/1.87.0-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libgimli-605c467c05f27091.rlib: no space left on device
Reference
Check build summary support
Error: buildx failed with: ERROR: failed to build: failed to solve: rpc error: code = Unknown desc = write /root/.rustup/toolchains/1.87.0-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libgimli-605c467c05f27091.rlib: no space left on device

* chore: split up dockerfiles

* chore: move required system libraries to base dockerfiles

* chore: add devel ci workflow for libs dockerfiles

* chore: join base and libs amd64 ci workflow

* refactor: use ghcr as cache for docker amd64

* refactor: use ghcr as cache for arm64

* chore: rename workflow steps

* chore: add release-beta workflow

* docs: update information about new image

* chore: restrict devel workflow and remove unused files